const data_1 = [
  {
    img: "https://m.media-amazon.com/images/I/71-2Z5rNG0L._AC_SX679_.jpg",
    title:
      "Senston N80-2 Pack Badminton Racquet, Professional Full Carbon Fiber Badminton Rackets Set with Grip",
    price: 89.99,
    min_discription: [
      "Senston N80 (2 racket)",
      "5U (75g-79g)",
      "G4 Grip",
      "The balance point: 295+-3MM",
      "Lengh: 675MM",
      "Prestring tension: 24LBS-26LBS",
    ],
    details: {
      Size: "One Size",
      Brand: "Senston",
      "Grip Size": "3 3/4 inches",
      "Sport Type": "Badminton",
      Material: "Carbon Fiber",
      "Skill Level": "Intermediate",
      "Frame Material": "Carbon Fiber",
      "Shaft Material": "Carbon Fiber",
      "Age Range": "Adult",
    },
    discription: [
      "RACKET PARAMETER: Senston N80 (2 racket) / 5U(75g-79g)/ G4 Grip/ The balance point: 295+-3MM/ Lengh:675MM/ Prestring tension: 24LBS-26LBS",
      "100% FULL CARBON FIBER MATERIAL: Senston N80 is made of full carbon fiber frame and shaft. Racket weight unstrung 75 grams, it is light. You can enjoy the badminton game longer and do not have shoulder pain caused by other heavier racket. It fell better when you playing. Carbon Fiber materials also enhance the strength of the racket, reduce to the risk of frame deformation",
      "SOLID CONSTRUCTION: The racket has SOLID construction with ONE-PIECE design outside and built-in T-joint inside. It have been further improve the STABILITY, achieve high-precision control performance. It also avoid the deformation caused by playing badminton, make racket more stable, play unparalleled power. The isometric square head shape frame structure and nanometer material enable it endure high pounds string, which can reach 30 pounds",
      "PERFECT DESIGNED DETAILS: the design of cone cover make the racket more in conformity with scientific theory of fluid dynamics to enhance the flexibility of controling the ball. Non-slip handle grip improve comfort, not easy to slide. Special and Powerful T-Joint Inside Design further improved the stability, achieve high-precision control performance. It also avoid the deformation caused by playing badminton, make racket more stable, play unparalleled power",
      "CUSTOMER SERVICE: If you have any problems after the purchase, you can feel free to contact us in any time.",
    ],
    website_link: "https://www.amazon.com/dp/B07N6685X6",
  },
  {
    img: "https://m.media-amazon.com/images/I/71snlkNDRBL._AC_SX425_.jpg",
    title: "YONEX Nanoray Light 18i Graphite Badminton Racquet (Black)",
    price: 50.99,
    min_discription: [
      "YONEX Nanoray Light 18i",
      "Material	Graphite",
      "Color Black",
      "Item Weight	77 Grams",
    ],
    details: {
      Size: "One Size",
      Brand: "YONEX",
      "Grip Size": "3 3/4 inches",
      "Sport Type": "Badminton",
      Material: "Graphite",
      "Skill Level": "All",
      "Frame Material": "Graphite",
      "Shaft Material": "Graphite",
      "Item Weight": "77 Grams",
      "Age Range": "Adult",
    },
    website_link: "https://www.amazon.com/dp/B07BY89TQY",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ATVK2KgRL._AC_SX425_.jpg",
    title:
      "Senston N90 Badminton Racket, 6U Lightweight Badminton Racquet, Professional 100% Full Carbon Badminton Racket with Grip",
    price: 40.99,
    min_discription: [
      "Senston N90 Series",
      "6U (68g-72g)",
      "G4 Grip",
      "The balance point: 295+-3MM",
      "Lengh: 675MM",
      "Prestring tension: 24LBS-26LBS",
    ],
    details: {
      Size: "One Size",
      Brand: "Senston",
      "Grip Size": "G4",
      "Sport Type": "Badminton",
      Material: "Carbon Fiber",
      "Skill Level": "Intermediate",
      "Frame Material": "Carbon Fiber",
      "Shaft Material": "Carbon Fiber",
      "Age Range": "Adult",
    },
    discription: [
      "Senston N90 Series: unstrung weight 6U(68g-72g)/ G4 Grip/ The balance point: 295+-3MM/ Lengh:675MM/ Prestring tension: 24LBS-26LBS",
      "100% FULL CARBON FIBER MATERIAL: The Flash racket is made of full carbon fiber frame, shaft and handle. Racket weight unstrung 70-75 grams, it is light. You can enjoy the badminton game longer and do not have shoulder pain caused by other heavier racket. It fell better when you playing. Carbon Fiber materials also enhance the strength of the racket, reduce to the risk of frame deformation",
      "SOLID CONSTRUCTION: The racket has SOLID construction with ONE-PIECE design outside and built-in T-joint inside. It have been further improve the STABILITY, achieve high-precision control performance. It also avoid the deformation caused by playing badminton, make racket more stable, play unparalleled power. The isometric square head shape frame structure and nanometer material enable it endure high pounds string, which can reach 28-30 pounds",
      "PERFECT DESIGNED DETAILS: the design of cone cover make the racket more in conformity with scientific theory of fluid dynamics to enhance the flexibility of controling the ball. Non-slip handle grip improve comfort, not easy to slide. Special and Powerful T-Joint Inside Design further improved the stability, achieve high-precision control performance. It also avoid the deformation caused by playing badminton, make racket more stable, play unparalleled power",
      "CUSTOMER SERVICE: If you have any problems after the purchase, you can feel free to contact us in any time.",
    ],
    website_link: "https://www.amazon.com/dp/B0BTD1F657",
  },
  {
    img: "https://m.media-amazon.com/images/I/814dI6hOipS._AC_SX425_.jpg",
    title:
      "TENGAOSI Professional Badminton Racket Set of 2 Unisex-Adult, The Racket is Made of Carbon Fiber High Tension Pre Strung Racquets",
    price: 89.99,
    min_discription: [
      "Set of 2 rackets",
      "4U (80g-84g)",
      "Professional badminton racket",
      "High elastic racket rod",
      "High elastic racket string",
      "The hitting sound is crisp",
      "Frame with high pound count",
    ],
    details: {
      Size: "One Size",
      Brand: "TENGAOSI",
      "Grip Size": "3 3/8 inches",
      "Sport Type": "Badminton",
      Material: "Carbon Fiber",
      "Skill Level": "Professional",
      "Frame Material": "Carbon Fiber",
      "Shaft Material": "Carbon Fiber",
      "Item Weight": "83 Grams",
      "Age Range": "Kid",
    },
    discription: [
      "SUPER TIGHT STRING: You never have to worry about losing a point because of wobbly or slack going strings. This are engineered to excellence with due focus on tightness in strings. This is a mark of dependability which every player seeks in his or her racket. Youll get the string is already attached when it arrives at your door. ",
      "EXCELLENT FOR ALL KINDS OF PLAYERS: Whether you are an amateur badminton player or a seasoned participant in title competitions, adults or children, you got the sturdiest racket option holding in your hand. With unquestionable durability, each of the TENGAOSI Badminton Rackets stays with you longer than any other brand. ",
      "SHAPE: The round-shape head with box-shape frame cross section gives TENGAOSI a unique and solid feeling.",
      "STRONG GRIP: Provided a technically designed grip with anti-slip tape, TENGAOSI Badminton racket facilitate you to stick to your game plan and earn points with a comfortable and firm grip .",
      "GET IT FAST: Serving up close to the net, playing such beautiful drive, smash and even drop shot, you can go on endlessly and easily because you have one of most glorious rackets in your hand. (Tags: badminton racket, TENGAOSI, sport, tool, games, indoor, outdoor)",
    ],
    website_link: "https://www.amazon.com/dp/B0978S8W82",
  },
  {
    img: "https://m.media-amazon.com/images/I/615jQ+MlEUL._AC_SX425_.jpg",
    title:
      "Senston - High Grade 2 Player Graphite Badminton Racket Set - Including 1 Badminton Bag/2 Rackets/2 Grip",
    price: 64.99,
    min_discription: [
      "Senston",
      "PACKAGE INCLUDES:",
      "2 Full Carbon Fiber Badminton Rackets",
      "2 Random Color Overgrip",
      "1 Badminton Bag (Badminton racquet has the Stringing about 25-26lbs)",
    ],
    details: {
      Size: "One Size",
      Brand: "Senston",
      "Sport Type": "Badminton",
      Material: "Graphite, Carbon Fiber",
      "Skill Level": "All",
      "Frame Material": "Carbon Fiber",
      "Shaft Material": "Carbon Fiber",
      "Age Range": "Adult",
    },
    discription: [
      "PACKAGE INCLUDES: 2 Full Carbon Fiber Badminton Rackets; 2 Random Color Overgrip; 1 Badminton Bag (Badminton racquet has the Stringing about 25-26lbs)",
      "100% FULL CARBON FIBER MATERIAL: the badminton set is made of full carbon fiber frame and shaft. Racket weight unstrung 5U(75-79g), it is light. You can enjoy the badminton game longer and do not have shoulder pain caused by other heavier racket. It fell better when you playing. Full carbon materials also enhance the strength of the racket, reduce to the risk of frame deformation",
      "SOLID CONSTRUCTION: The racket has SOLID construction with ONE-PIECE design outside and built-in T-joint inside. It have been further improve the STABILITY, achieve high-precision control performance. It also avoid the deformation caused by playing badminton, make racket more stable, play unparalleled power",
      "PERFECT DESIGNED DETAILS: the design of cone cover make the racket more in conformity with scientific theory of fluid dynamics to enhance the flexibility of controling the ball. Non-slip handle grip improve comfort, not easy to slide",
      "CUSTOMER SERVICE: If you have any problems after the purchase, you can feel free to contact us in any time.",
    ],
    website_link: "https://www.amazon.com/dp/B08CGPHRZB",
  },
];

const data_2 = [
  {
    img: "https://m.media-amazon.com/images/I/71se2u2vMzL._AC_SX425_.jpg",
    title: "Ace Badminton Birdies, Badminton shuttlecocks",
    price: 8.99,
    min_discription: [
      "Badminton shuttlecocks",
      "12 Pcs Set shuttlecocks",
      "Birdie Balls Nylon Feather with Strong Cork Head",
      "Sturdy and Well-Balanced",
    ],
    details: {
      Size: "One Size",
      Brand: "Ace Badminton",
      Set: "12 Pcs Set shuttlecocks",
      "Sport Type": "Badminton",
      Material: "Nylon Feather",
      "Skill Level": "Any",
      "Age Range": "Child and Above",
    },
    discription:
      "When it comes to badminton having a great racket is important, but having high-quality birdies is essential. That’s why we created Ace Birdies Badminton Shuttlecocks with 100% nylon feathers, high-quality cork tips, neon yellow colors to ensure a better game from start to finish. Designed to fly with more stability, stand up to heavier hits, and supporting practice and professional play these shuttlecocks can help you get the most out of every match. Challenge your friends, practice at the park, or host fun neighborhood tournaments with quality badminton shuttlecocks made for kids and adults.",
    website_link: "https://www.amazon.com/dp/B09WK3KSSS",
  },
  {
    img: "https://m.media-amazon.com/images/I/716ffNouiEL._AC_SX425_.jpg",
    title:
      "KEVENZ Goose Feather Badminton Shuttlecocks with Great Stability and Durability",
    price: 14.99,
    min_discription: [
      "Badminton shuttlecocks",
      "12 Pcs Set shuttlecocks",
      "Great Stability and Durability",
      "High Speed Badminton Birdies",
      "100% infrared selection of goose feathers quality, feather hair straight and thick, good strength, enhance the badminton resistance",
      "100% test badminton rotation, to ensure that the badminton flight stability",
      "Goose feathers are treated with special formula, smooth and soft",
    ],
    details: {
      Color: "White",
      Sold: "12 Pack profession badminton shuttlecocks",
      Brand: "KEVENZ",
      "Sport Type": "Badminton",
      Material: "Advanced Goose Feather",
      "Skill Level": "Any",
      "Age Range": "Child and Above",
    },
    discription: [
      "Kevenz badminton production line inspection process:",
      "1. production line workers will pick quality goose feathers",
      "2. The computer automatically detects the goose feather shape",
      "3. Badminton rotation stability test",
      "4. Badminton flight stability test",
    ],
    website_link: "https://www.amazon.com/dp/B07G281S59",
  },
  {
    img: "https://m.media-amazon.com/images/I/81wvzkguAiL._AC_SY879_.jpg",
    title: "Champion Sports Nylon Outdoor Shuttlecocks",
    price: 9.99,
    min_discription: [
      "Badminton shuttlecocks",
      "Durable nylon construction",
      "Nylon base for outdoor play",
      "Pack of six (6) shuttles per tube",
      "The Package Weight Of The Product Is 0.36 Pounds",
    ],
    details: {
      Color: "White",
      Sold: "6 Pack badminton shuttlecocks",
      Brand: "Champion Sports",
      "Sport Type": "Badminton",
      Material: "nylon",
      "Skill Level": "Any",
      "Age Range": "Child and Above",
    },
    website_link: "https://www.amazon.com/dp/B002M2NUOW",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ekKWkmbqL._AC_SX425_PIcountsize-4,TopRight,0,0_SH20_.jpg",
    title:
      "ZHENAN LED Badminton Shuttlecocks Dark Night Glow Birdies Lighting for Outdoor & Indoor Sports Activities (Nylon_5pcs)",
    price: 16.99,
    min_discription: [
      "Badminton shuttlecocks",
      "LED Badminton Birdies",
      "Nylon badminton, SMD lamps, Electronic products,100% safe",
      "The LED lights can be switched on and off easily",
      "With these led shuttlecocks the fun is just beginning when the sun goes down",
      "Approximate life span of 50 hours each to keep the fun going for a good long time",
      "5Pcs/box: Red, Blue, Green, Yellow, Colorfull flashing",
    ],
    details: {
      Color: "Multi-Color",
      Sold: "5 Pack profession badminton shuttlecocks",
      Brand: "ZHENAN LED",
      "Sport Type": "Badminton",
      Material: "Nylon badminton, SMD lamps, Electronic products",
      "Skill Level": "Any",
      "Age Range": "Child and Above",
    },
    discription: [
      "This LED badminton set is perfect for playing in the dark night. It just makes badminton even more fun for kids or adults. Enjoy!",
      "360-degree view/ soft/ clear/ comfortable/ visible. LIGHT UP at night with various beautiful colors!",
    ],
    website_link: "https://www.amazon.com/dp/B07176ZCWW",
  },
  {
    img: "https://m.media-amazon.com/images/I/71H4ddu8UXL._AC_UY395_.jpg",
    title:
      "Condromly Women's Men's Luff 85 Lightweight Cushioning Pickleball Court Shoes",
    price: 49.99,
    min_discription: [
      "Rubber sole",
      "Lightweight Material",
      "Non-Slip Outsole",
      "Midsole developed by UltraLite EVA foam midsole technology",
      "Comfort Upper made of synthetic microfiber",
      "MULTI-PURPOSE",
    ],
    discription: [
      "Rubber sole",
      "LIGHTWEIGHT MATERIAL: LEFUS court shoes have improved the overall constrcution design, and ultralight materials have been used in the microfiber upper and MD sole. The net weight of the whole pair of shoes(size 7) is only approx 17.6 oz.",
      "NON-SLIP OUTSOLE: The outsole features a full-length non-marking rubber which provides unsurpassed durability, and the honeycomb groove sole prints enhanced the friction to provide a great grip and maintain balance and stability during your play.",
      "MIDSOLE: Self-developed UltraLite EVA foam midsole technology has provided superior resilience and flexibility for the sole. And an anti-torsion TPR panal is embedded in the midsole to enhance the torsion resistance and provide extra arch support.",
      "COMFORT UPPER: The shoe upper is made of synthetic microfiber, which has perforations at the forefoot part, and these holes could help keep the interior of the shoes in a breathable and dry condition. The wrap-up of the whole vamp is just perfect.",
      "MULTI-PURPOSE: These shoes are designed for various athletic activities such as pickleball, tennis, badminton, volleyball, walking. With the outsole designed specifically for court sports, these shoes could perform well on indoor or outdoor courts.",
    ],
    website_link: "https://www.amazon.com/dp/B09Z21MGZM",
  },
  {
    img: "https://m.media-amazon.com/images/I/41ukyq631nL._AC_SX425_.jpg",
    title: "Yonex Power Cushion 50 Men Badminton Shoes (White/Blue)",
    price: 110.99,
    min_discription: [
      "Rubber sole",
      "ERGOSHAPE",
      "great comfort and stability",
      "great comfort, stability and durability",
      "MULTI-PURPOSE",
    ],
    discription:
      'The new PC 50 badminton shoe is the "value for money" model of Yonex for the new season. This model is designed for players who want a shoe with great comfort and durability. Thanks to "POWER CUSHION" great cushioning and smooth impact are achieved. With the system "ERGOSHAPE" you get great comfort and stability in the front of the foot. With the system "HEXAGRIP" 3% more grip is achieved on the sole and 10% more lightness than a conventional sole. Thanks to all this we get great comfort, stability and durability in the shoe.',
    website_link: "https://www.amazon.com/dp/B0BPDM6MVG",
  },
  {
    img: "https://m.media-amazon.com/images/I/51daeuYEynL._AC_SX425_.jpg",
    title: "Yonex Power Cushion 50 Men Badminton Shoes (Dark Grey)",
    price: 109.99,
    min_discription: [
      "Upper Material: P.U. Leather, Double Russel Mesh",
      "Midsole: Power Cushion, Synthetic Resin",
      "Outsole: Rubber",
      "Color: Dark Grey",
    ],
    discription:
      "Affordable entry-level Power Cushion Badminton Shoe. Ideal for beginners or casual players. The Ergoshape provides more comfort and stability in the forefoot and toe area. Power Cushion is popular due to its shock absorption. It absorbs shock and eventually transfer the shock energy into power. YONEX has experiment this by dropping a raw egg 7m above a Power Cushion sheet. The result is it bounces back 4m without any damage.",
    website_link: "https://www.amazon.com/dp/B0BPF1HGDK",
  },
  {
    img: "https://m.media-amazon.com/images/I/71KjPeUVjZL._AC_UX395_.jpg",
    title:
      "WHITIN Men's Cross-Trainer | Barefoot & Minimalist Shoe | Zero Drop Sole | Wide Toe Box",
    price: 43.99,
    min_discription: [
      "Rubber sole",
      "Anatomical shape provides natural comfort",
      "Adaptive materials and minimalist construction",
      "Zero drop from heel to toe for a natural stride",
      "Our vegan friendly footwear uses 0% animal products",
      "It is true to size, please order your normal size",
    ],
    discription: [
      "Rubber sole",
      "Package Dimensions : 16.02 x 11.61 x 5.35 inches; 1.98 Pounds",
      "Department : Mens",
      "Date First Available : August 27, 2020",
      "ASIN : B07NQ47CNN",
    ],
    website_link: "https://www.amazon.com/dp/B08CKFWGV1",
  },
  {
    img: "https://m.media-amazon.com/images/I/41SNmg+eDaL._AC_.jpg",
    title: "Yonex AC402EX Towel Grip 100% Cotton GRAP",
    price: 14.99,
    min_discription: [
      "100% Cotton",
      "Towel Grip",
      "AC402EX",
      "Absorbs Sweat",
      "Prevents Slippings",
      "Comfortable Towel Grip with Improved Absorbency",
    ],
    details: {
      Color: "Sax",
      Brand: "YONEX",
      Material: "Cotton",
      "Number of Items": 1,
      "Product Care Instructions": "Machine Wash",
    },
    website_link: "https://www.amazon.com/dp/B000I12P3G",
  },
  {
    img: "https://m.media-amazon.com/images/I/61I+0qXmzcL._AC_SX425_.jpg",
    title:
      "DEARLIVES Tennis Racket Grip Tape,Badminton Grip Tape with Anti Slip",
    price: 11.99,
    min_discription: [
      "Widen Hand: The width of tennis racket grips is 2.5cm(0.98in)",
      "The use area is large, providing players with more comfortable feel.",
    ],
    details: {
      Color: "Multi-Color",
      Brand: "DEARLIVES",
      Material: "Rubber",
      "Number of Items": 1,
    },
    website_link: "https://www.amazon.com/dp/B07Y2NKTS8",
  },
  {
    img: "https://m.media-amazon.com/images/I/41OuyDF4mJL._AC_SX425_.jpg",
    title: "Yonex Super Grap Deep Purple 3 Pack",
    price: 8.99,
    min_discription: [
      "Includes grip tape",
      "Great for any racquet sport - Tennis, Badminton, Squash, Racquetball",
      "Package contains one roll of 3 strips of overgrip",
    ],
    details: {
      Color: "Deep Purple",
      Brand: "YONEX",
      Material: "Synthetic",
      "Number of Items": 1,
    },
    discription:
      "Yonex Super Grap is a top quality overgrip for tennis, badminton, or any sport. Also great for wrapping hockey sticks and baseball bats. Each strip is 120 cm (about 48 inches) long; plenty for a tennis racquet grip.",
    website_link: "https://www.amazon.com/dp/B00JG9IFXK",
  },
  {
    img: "https://m.media-amazon.com/images/I/710eXLqucVL._AC_SX425_.jpg",
    title:
      "12 Pieces Tennis Badminton Racket Overgrips for Anti-Slip and Absorbent Grip",
    price: 9.99,
    min_discription: [
      "Package contents: 12 pieces overgrips in black, white, green, yellow, pink, red, blue, grey, orange, purple, light blue, fluorescence green, each color 1 piece;",
      "Let you easily distinguish each racket",
    ],
    details: {
      Color: "Multi-Color",
      Brand: "Pangda",
      "Sport Type": "Tennis, Badminton",
      Material: "Faux Leather",
    },
    discription: [
      "Package contents: 12 pieces overgrips in black, white, green, yellow, pink, red, blue, grey, orange, purple, light blue, fluorescence green, each color 1 piece; Let you easily distinguish each racket",
      "Application: the racket overgrip is suitable for tennis, badminton, squash, racket ball racket, also fit for fishing rods, bike handlebars, motorbike handlebars, etc.",
      "Anti-slip overgrip: with good sweat absorption and great slip resistance, the tennis grip can ensure lossless batting strength, preserve and prolong the lifetime of your racket handles",
      "Dimension (length x width x thickness): approx. 43.3 x 1 x 0.03 inch/ 110 x 2.5 x 0.075 cm, the thin thickness provides a comfortable feeling to touch",
      "Durable material: these racket overgrips are made of good quality PU material with thin and good-stretch felt surface; And attached adhesive pads",
    ],
    website_link: "https://www.amazon.com/dp/B07PJ9J4RL",
  },
  {
    img: "https://m.media-amazon.com/images/I/6184wdgjMhL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "GAMMA Supreme Overgrips",
    price: 6.99,
    min_discription: [
      "TOP-PERFORMANCE RACQUET GRIP TAPE: GAMMA Supreme Overgrip will help you rule the court",
      "These soft grip-tape wraps are made to be long-lasting and feature absorbent material combined with extreme durability to keep up with your game",
    ],
    details: {
      Color: "Black, Grey, Pink, White",
      Brand: "GAMMA",
      Material: "Synthetic",
      "Number of Items": 1,
    },
    discription: [
      "TOP-PERFORMANCE RACQUET GRIP TAPE: GAMMA Supreme Overgrip will help you rule the court; These soft grip-tape wraps are made to be long-lasting and feature absorbent material combined with extreme durability to keep up with your game.",
      "READY FOR MANY GAMES: This sports grip tape is perfect for taking many sports to the next level; Wrap our overgrip on a variety of racquet handles, including tennis, pickleball, squash, badminton, and racquetball racquets.",
      "EASY AND QUICK APPLICATION: Spend less time preparing and more time on the court with our overgrip wrap; This tacky grip provides fast, easy, no-fuss applications and even fits on extra-long racquets.",
      "ABSORBENT MATERIAL: Keep your hands dry and comfortable with our overgrip tape for handles; The durable material works to absorb sweat during intense matches, allowing you to play with greater precision.",
      "NEVER STOP PLAYING: Founded on a history of unique innovation, GAMMA Sports strives to support every athlete, from experienced professionals to excited beginners; Our products are made to inspire everyone to never stop playing and improving.",
    ],
    website_link: "https://www.amazon.com/dp/B000HEKHCA",
  },
  {
    img: "https://m.media-amazon.com/images/I/61eEHwPuiFL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "YONEX BG65 Badminton String USA Original Version",
    price: 11.99,
    details: {
      Color: "Yellow",
      Brand: "YONEX",
      "Sport Type": "Badminton",
      "Core Material": "High Polymer Nylon Multifilament",
      "Outer Material": "Special Braided High Polymer Nylon Fibre",
      "Item Weight": "0.02 Pounds",
      Length: "10m (33 feet)",
      Gauge: "22 / 0.70 mm",
    },
    website_link: "https://www.amazon.com/dp/B000ROMI2M",
  },
  {
    img: "https://m.media-amazon.com/images/I/61mK6oahbmL._AC_SX425_.jpg",
    title: "Yonex BG 80 Badminton String",
    price: 13.99,
    details: {
      Color: "Yellow",
      Brand: "YONEX",
      "Sport Type": "Badminton",
      Material: "High-Intensity Multifilament Nylon",
      "Item Weight": "0.09 Pounds",
      Length: "10m (33 feet)",
      "Age Range": "Adult",
      "High Repulsion": null,
      "Medium Feeling": null,
    },
    discription:
      "The high-intensity nylon core gives greater durability than normal nylon while a high-polymer nylon outer provides sharp feeling and high repulsion - exceptional all-round performance from an extra-fine string.",
    website_link:
      "https://www.amazon.com/dp/B002BAZBFG?ref_=cm_sw_r_cp_ud_dp_CNE191J6QPYKA9X0MR8S&th=1",
  },
  {
    img: "https://m.media-amazon.com/images/I/51+SNEdlWVL._AC_SX425_.jpg",
    title: "Yonex BG 65 Ti 200m Racquet String",
    price: 123.99,
    details: {
      Color: "White",
      Brand: "YONEX",
      "Sport Type": "Badminton",
      "Core Material": "High Polymer Nylon Multifilament",
      "Outer Material": "Special Braided High Polymer Nylon Fibre",
      "Item Weight": "150 Grams",
      Length: "200m",
      "Compound Titanium Hydride": null,
      "Age Range": "Adult",
    },
    discription:
      "The compound titanium hybrid coating provides a sharp but comfortable feel at impact. Designed for hard hitters.",
    website_link: "https://www.amazon.com/dp/B000ASBT4S",
  },
  {
    img: "https://m.media-amazon.com/images/I/71XnI3nzbdL._AC_SX425_.jpg",
    title:
      "Tier One Sports T1-Firewire - Co-Poly Tennis String for Ultimate Spin",
    price: 134.99,
    details: {
      Color: "Red, Black",
      Brand: "T1-Firewire",
      "Sport Type": "Badminton",
      Material: "High Polymer Nylon",
      "Item Weight": "16 Grams",
      Length: "12.2m (40 feet)",
      Gauge: "16 / 1.30 mm",
    },
    discription: [
      "An innovative, triangular shaped, monofilament string, offers one of the best ball bites and spin potentials in the string industry. Exceptional tension stability and its crisp but arm-friendly playing experience makes this string the front runner for the competitive weekend warrior.",
      "KEY FEATURES: Provides Maximum Ball Bite and Tension Stability.",
      "RECOMMENDED PLAYING LEVEL: NTRP: 3.0-5.0, UTR: 2.5-9.5 (intermediate - advanced level).",
      "GAUGES: 16g (1.30mm). 17g (1.25mm), 18g (1.20mm).",
      "LENGTHS: Sets: 12.2mm/40ft, Reels: 200m/656ft, COLORS: Red, Black.",
    ],
    website_link: "https://www.amazon.com/dp/B01K4A16GM",
  },
  {
    img: "https://m.media-amazon.com/images/I/61LPZBLSeOL._AC_SX425_.jpg",
    title:
      "Senston Badminton Racket Bag,Single Shoulder Racket Bag 6 Racquet Bag ,Waterproof And Dustproof",
    price: 30.99,
    details: {
      Color: "Black",
      Size: "One Size",
      Brand: "Senston",
      "Sport Type": "Badminton",
      Material: "Polyester",
    },
    discription: [
      'Racket Bag Dimensions: L: 28.34" x H: 11.4" x W: 7.1"',
      "Large-capacity, two main bag, three secondary bags. It can accommodate 5-6 badminton racquets and 3-4 tennis racquets, or jackets and shoes.",
      "auxiliary bag has holes",
      "good ventilation effect, keeping items ventilation",
      "Fabric: polyester PU",
    ],
    website_link: "https://www.amazon.com/dp/B01A8JMHOY",
  },
  {
    img: "https://m.media-amazon.com/images/I/81RkwRK1QjL._AC_SX425_.jpg",
    title:
      "Tolaccea Tennis Bag, Large Tennis Backpack for Men and Women, Tennis Racket Bag holds 6 Rackets with Shoe Compartment",
    price: 39.99,
    min_discription: [
      "Large Tennis Backpack: Tolaccea tennis bag is equipped with 2 main large compartments, a shoe compartment, a wet compartment, a front compartment",
      "Large capacity to hold up to 6 rackets, shoes, clothes, water bottle, wet towel, and so on",
      "Dimensions:28.7”* 11.8” *9”(L*W*H).",
    ],
    details: {
      Color: "Gray",
      Size: "Large",
      Brand: "Tolaccea",
      "Sport Type": "Badminton",
      Material: "Polyester",
    },
    discription: [
      "Large Tennis Backpack: Tolaccea tennis bag is equipped with 2 main large compartments, a shoe compartment, a wet compartment, a front compartment. Large capacity to hold up to 6 rackets, shoes, clothes, water bottle, wet towel, and so on. Dimensions:28.7”* 11.8” *9”(L*W*H).",
      "Padded Straps for Backpack: Designed with two hidden shoulder straps, you can carry it like a backpack easily even it holds all the heavy tennis gears.",
      "Ventilated Shoe Compartment: External big shoe compartment at the bottom of the tennis racket bag separates your shoes from the rest of your equipment free from dirt and mud. The ventilated hole keeps your tennis equipment dry and fresh.",
      "Wet Compartment: You can freely to put your water bottle, dirt or wet sporting clothes and towels in the wet compartment.",
      "Durable Tennis Bags: Made of high quality durable material, the tennis racket backpack has better tear and water resistant. Padded straps and airflow back to make your back more comfortable.This tennis racket bags can be used as many outdoor activities bag, such as a pickle ball paddles bag, badminton racquet bag, squash racquet bag and so on. Also it can be used as a travel backpack.",
    ],
    website_link: "https://www.amazon.com/dp/B0B5H9D9N4",
  },
  {
    img: "https://m.media-amazon.com/images/I/51CGeWwDD0L._AC_SX425_.jpg",
    title: "YONEX Pro Racquet Bag 9 Pack",
    price: 77.99,
    min_discription: [
      "Yonex Pro Racquet Bag 92229",
      "Color: Green Purple",
      "Size (LxWxH): 78 x 38 x 34 cm (30.7 x 14.9 x 13.3 inch)",
      "Polyester 100%",
      "Available As A Backpack / Adjustable Buckle /Shoe Pocket / Thermo Guard",
    ],
    details: {
      Color: "Green, Purple",
      Size: "One Size",
      Brand: "YONEX",
      "Sport Type": "Badminton",
      Material: "Polyester",
    },
    discription:
      "The Yonex Pro Racquet 9 Pack Bag is a great option for serious players. This larger bag provides you the ability to carry up to 9 racquets at once, along with other gear. The Pro 9 Pack features a better shape retention and plenty of interior space, including a separate wet/shoe compartment on the bottom, with multiple access points. Never arrive at the tennis courts without something ever again.",
    website_link: "https://www.amazon.com/dp/B09Z78FTWW",
  },
  {
    img: "https://m.media-amazon.com/images/I/81TJhcQiXSL._AC_SX425_.jpg",
    title: "Yonex Badminton Bag SUNR 2215 BT5 Black Red",
    price: 49.99,
    min_discription: [
      "100% Polyster",
      "Main Compartment",
      "Racquets Compartmnet",
      "Accessories Compartment",
      "Sling Bag",
    ],
    details: {
      Color: "Black Red",
      Size: "One Size",
      Brand: "YONEX",
      "Sport Type": "Badminton",
      Material: "Polyester",
    },
    website_link: "https://www.amazon.com/dp/B0B4SRXWZ3",
  },
  {
    img: "https://m.media-amazon.com/images/I/81HS4QhFmtS._AC_SX425_.jpg",
    title: "Portable Tennis Net,Stainless Steel Poles Badminton Net Set",
    price: 65.99,
    min_discription: [
      "Badminton and more, Game On!",
      "With adjustable height function(37-63 in)",
      "Zicon portable badminton net is suitable to play badminton, tennis, soccer tennis, modified volleyball and pickleball",
      "You can play on backyard, beach, driveway and any flat area",
      "It’s ideal for adults’ and kids’ casual play and sports training.",
    ],
    details: {
      Color: "White",
      Size: "13.5 FT",
      Brand: "Zicon",
      "Sport Type": "Badminton",
      Material: "Nylon",
      "Item Dimensions (LxWxH)": "122.05 x 39.37 x 62.99 inches",
    },
    discription: [
      "Badminton and more, Game On!: With adjustable height function(37-63 in), Zicon portable badminton net is suitable to play badminton, tennis, soccer tennis, modified volleyball and pickleball. You can play on backyard, beach, driveway and any flat area. It’s ideal for adults’ and kids’ casual play and sports training.",
      "Durable and Rust Resistant: Unlike most other similar net set's poles that make of thin and easy-to-fold galvanized pipes,Zicon badminton net set comes with stainless steel poles, and superior quality nylon net, to ensure rust and all weather resistant. With sturdy construction, you can use at various places without worries.",
      "Portable and Convenient Carry: Zicon nylon net is lightweight and foldable, the poles are connected by a durable bungee cord and assemble in bunch, no need to worry any parts losing. With the durable and light carrying bag, it’s convenient to carry, great for holiday, camping and parties having fun with families and friends.",
      "Easy Setup and Takedown: No stakes and tools required, you can easily set up and takedown within 3-5 minutes. It’s even workable for a kid. You can also rapidly adjust the height as per your needs.",
      "What You Get: 1 badminton nylon net with high density 0.79x0.79 inch small mesh to make sure not stuck balls; 1 lightweight and durable bag; Optimal service and limitless fun of sports. You can reach for us anytime for question or suggestion.",
    ],
    website_link: "https://www.amazon.com/dp/B08DD6SYYB",
  },
  {
    img: "https://m.media-amazon.com/images/I/81sV8C250UL._AC_SX425_.jpg",
    title: "JOOLA HIT MIT Adjustable Height Portable Badminton Net Set",
    price: 49.99,
    min_discription: [
      "ADJUSTABLE NET FOR MULTI SPORT USE",
      "NET DESIGNED FOR INDOOR OR OUTDOOR COURTS (NO STAKES REQUIRED)",
      "EASY TO PUT UP AND TAKE DOWN",
      "EASY TRANSPORT AND CONVENIENT STORAGE",
      "BONUS ITEMS",
    ],
    details: {
      Color: "White",
      Size: "10 FT",
      Brand: "JOOLA",
      "Sport Type": "Badminton",
      Material: "Nylon",
    },
    discription: [
      "ADJUSTABLE NET FOR MULTI SPORT USE: Choose between THREE height settings for different playing or practice options. Use the net in the lowest setting as a safety barrier or barricade to stop balls from rolling into the street; a great choice for parents.",
      "NET DESIGNED FOR INDOOR OR OUTDOOR COURTS (NO STAKES REQUIRED): Whether for badminton, soccer tennis, lawn tennis, or pickleball, this net is a great choice for your family and friends. Play anywhere - the grass, beach, backyard, or inside the school gym.",
      "EASY TO PUT UP AND TAKE DOWN: Setup takes less than 5 minutes! Takedown of the rust resistant net stand is also quick and easy. High quality nylon thread is used for the net to ensure years of fun and enjoyment without the worry of the net tearing.",
      "EASY TRANSPORT AND CONVENIENT STORAGE: The durable sport net set is lightweight, foldable, portable, and practical. INCLUDES carrying bag case to store the poles and net and take with you to the gym, park, camping, gatherings, or birthday parties.",
      "BONUS ITEMS: What kind of playing court is official without the lines? Included are four ground stakes and border out of bounds lines for creating your own court for competitive game play.",
    ],
    website_link: "https://www.amazon.com/dp/B071YPVRV7",
  },
  {
    img: "https://m.media-amazon.com/images/I/51Jn0RIZ4xL._AC_SX425_.jpg",
    title:
      "KIKILIVE Weiershun Portable Badminton Net with Stand Carry Bag, Folding Volleyball Tennis Badminton Net",
    price: 28.99,
    min_discription: [
      "The badminton net is portable, foldable and lightweight",
      "the package size is about 60cm, the set is only about 750g",
      "Open size: 300cm x 150cm",
      "You can bring the fun anywhere",
    ],
    details: {
      Color: "White yellow",
      Brand: "KIKILIVE",
      "Sport Type": "Badminton",
      Material: "Carbon Fiber, Polyester, PU, Stainless Steel",
      "Item Dimensions (LxWxH)": "19.5 x 4.3 x 4.2 inches",
    },
    discription: [
      "Simple Design: The badminton net is portable, foldable and lightweight, the package size is about 60cm, the set is only about 750g. Open size: 300cm x 150cm. You can bring the fun anywhere. (ONLY A Badminton Net & Stand Carry Bag)",
      "Lightweight Durability: This folding badminton net set is made of carbon fiber, polyester, PU,and stainless steel, ensure durable net and solid metal hooks",
      "Easy to Use: Play badminton, volleyball, tennis on the beach, driveway, backyards and any flat area! Portable badminton net set is great for parties, camping, and family holidays",
      "Metal Rings: Double guyline with tension rings allow for quick adjustments that ensure the net remains taut, even during rough play",
      "100% Satisfaction: If you want something durable, then this is the best deal you can ever make. Use the portable badminton net set indoors & outdoors without worries",
    ],
    website_link: "https://www.amazon.com/dp/B087BWMVTK",
  },
  {
    img: "https://m.media-amazon.com/images/I/71lqi7lYXSL._AC_SX425_.jpg",
    title: "Four Way Volleyball Net 14ft x 14ft Height Adjustable",
    price: 90.99,
    min_discription: [
      "Build for Tough, this volleyball and badminton net is designed for sturdiness",
      "The net is double machine sewn to avoid ripe or torn, especially the cross connection portion, there are some enhancement added",
      "Net dimension: 14’x14’, with each mesh 1.5” x 1.5” knotless strong PE materials.",
    ],
    details: {
      Color: "Green",
      Brand: "Zdgao",
      "Sport Type": "Badminton",
      Material: "Polyester",
    },
    discription: [
      "Build for Tough, this volleyball and badminton net is designed for sturdiness. The net is double machine sewn to avoid ripe or torn, especially the cross connection portion, there are some enhancement added. Net dimension: 14’x14’, with each mesh 1.5” x 1.5” knotless strong PE materials.",
      "Strong Net Support, Standing Solid! Zdgao four way volleyball badminton game set has strong poles system, 7” ground anchors and Nylon drawstrings to serving this net standing firmly even in a windy or rainy day. And the metal poles is powder-coated for all weather resistance, no pain to taking this 4 way volleyball set down.",
      "Easy Set up volleyball net. Unlike others four square game set, Zdgao four square badminton volleyball combo set is super easy to set up, the drawstrings are upgraded for easier tension adjustment. The assembly instruction is packed as well!",
      "Height adjustment-7.4’/7’/5’. This outdoor volleyball net heavy duty set is height adjustable and with press-lock button system for easy height conversion. The full height is 7.4’ for both men or women playing volleyball game, 7’ suitable for teens or children, and 5’ for kids or badminton game.",
      "Complete Game Set for Whole Family Fun! 4 way volleyball badminton combo game is one of the most suitable backyard or beach game that is safe and interesting! This game come with a soft volleyball and storage bag, boundary line, rubber hammer, carrying bag, and ball pump with needle. It would be a good time at your party or family gathering!",
    ],
    website_link: "https://www.amazon.com/dp/B0BPPK52LV",
  },
  {
    img: "https://m.media-amazon.com/images/I/71bNmYlxcmL._AC_SX425_.jpg",
    title:
      "Portable Badminton Net Set for Tennis, Soccer Tennis, Kids Adult Volleyball",
    price: 15.99,
    min_discription: [
      "Made of PE net to avoid tear, ensure durability",
      "With sturdy construction, use indoors and outdoors without worries.",
    ],
    details: {
      Color: "Black",
      Size: "3.1m",
      Brand: "Denpetec",
      "Sport Type": "Badminton",
      Material: "Nylon",
    },
    discription: [
      "Made of PE net to avoid tear, ensure durability. With sturdy construction, use indoors and outdoors without worries.",
      "Play badminton, modified volleyball, tennis, soccer tennis and pickleball on the beach, driveway, backyards and any flat area! Our net is great for parties, camping, and family holidays.",
      "With its convenient carrying case, you can bring the fun anywhere. Our portable net is lightweight & foldable,you can take your Tennis competitions anywhere,save-space and easy to carry for travel",
      "Ideal For Tennis, Badminton,Volleyball or other over-the-net sports,and also the best gift for your children and family to play together on Garden Schoolyard Backyard,Beach, Driveway,or any flat area!",
      "Have fun together,Play badminton, kids bolleyball, soccer, tennis with children, adults, friends or families on backyards, indoor/outdoor court, beach, lawn or any flat surface.",
    ],
    website_link: "https://www.amazon.com/dp/B091HYZJVB",
  },
];
